# Generated by Django 5.1.6 on 2025-02-17 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='reference_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('waste_report', 'Waste Report'), ('pickup_request', 'Pickup Request'), ('status_update', 'Status Update'), ('pickup_status', 'Pickup Status'), ('educational', 'Educational Content')], max_length=20),
        ),
    ]
