# Generated by Django 5.1.6 on 2025-02-17 02:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_notification_options_notification_reference_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalcontent',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='educational_content'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pictures'),
        ),
        migrations.AlterField(
            model_name='wastereportmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='waste_reports'),
        ),
    ]
